api:
  dashboard: true
  # insecure: true # Don't do that in production

# Entrypoints
entryPoints:
  web:
    address: :80

  websecure:
    address: :443
    
# Providers
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

metrics:
  datadog:
    addEntryPointsLabels: true
    address: datadog-agent:8125

tracing:
  datadog:
    localAgentHostPort: datadog-agent:8126

log:
  filePath: "/traefik/logs/traefik.log"
  format: json

accessLog:
  filePath: "/traefik/logs/access.log"